### ISSUE TITLE
html静态页就可以实现？？？

### ISSUE THREAD

**Issue by s0urcelab** [zhouyelihua/wifidogAuth#1]
不需要后端程序？测试可行？？

**Comment by zhouyelihua** [comment]
这个用python的webpy运行起来就是充当服务器的功能

**Comment by zhouyelihua** [comment]
我错了，这个是我fork的，我以为是我自己写的那个

**Comment by zhouyelihua** [comment]
这个是我自己实现的，有详细的路由破解的过程，你可以参考一下https://github.com/zhouyelihua/wifidog-yaha

**Comment by s0urcelab** [comment]
额，那这个你fork的可以用么？我就是好奇，纯html可以正常工作么？

**Comment by zhouyelihua** [comment]
那个应该不可以吧，我之前的是可以的webpy程序里面有实现的，你可以参考一下，那个readme
